{
 "title": "OpenTelemetry Collector",
 "description": "Visualize OpenTelemetry (OTEL) collector metrics (tested with OTEL contrib v0.88.0)",
 "tags": [
  "opentelemetry",
  "monitoringartist"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   { "name": "minstep", "label": "Min step", "query": "10s,30s,1m,5m" },
   { "name": "metric", "label": "Base metric", "query": "Rate : rate, Count : increase" },
   {
    "name": "receiver",
    "label": "Receiver",
    "query": {
     "query": "query_result(avg by (receiver) ({__name__=~\"otelcol_receiver_.+\",k8s_cluster_name=\"$cluster\"}))"
    }
   },
   {
    "name": "processor",
    "label": "Processor",
    "query": {
     "query": "query_result(avg by (processor) ({__name__=~\"otelcol_processor_.+\",k8s_cluster_name=\"$cluster\"}))"
    }
   },
   {
    "name": "exporter",
    "label": "Exporter",
    "query": {
     "query": "query_result(avg by (exporter) ({__name__=~\"otelcol_exporter_.+\",k8s_cluster_name=\"$cluster\"}))"
    }
   },
   {
    "name": "grouping",
    "label": "Additional groupping",
    "query": "None (basic metrics) :  , By transport (detailed metrics) : \\,transport, By collector pod name : \\,k8s_pod_name"
   },
   {
    "name": "suffix",
    "label": "Suffix",
    "query": {
     "query": "query_result({__name__=~\"otelcol_process_uptime_seconds_total.+\",k8s_cluster_name=\"$cluster\"})"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(otelcol_process_uptime_seconds_total,k8s_cluster_name)"
    }
   },
   {
    "name": "collector_pod_name",
    "label": "Collector Pod name",
    "query": {
     "query": "label_values(otelcol_process_uptime_seconds_total{k8s_cluster_name=\"$cluster\"},k8s_pod_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Receivers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Spans ${metric:text} - $collector_pod_name",
   "type": "timeseries",
   "description": "Accepted: count/rate of spans successfully pushed into the pipeline.\nRefused: count/rate of spans that could not be pushed into the pipeline.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(${metric:value}(otelcol_receiver_accepted_spans_total{receiver=~\"$receiver\",k8s_cluster_name=\"$cluster\", k8s_pod_name=~\"$collector_pod_name\"}[2$__rate_interval])) by (receiver $grouping)",
     "legendFormat": "Accepted: {{receiver}} {{transport}} {{k8s_pod_name}}"
    },
    {
     "expr": "sum(${metric:value}(otelcol_receiver_refused_spans_total{receiver=~\"$receiver\",k8s_cluster_name=\"$cluster\", k8s_pod_name=~\"$collector_pod_name\"}[2$__rate_interval])) by (receiver $grouping)",
     "legendFormat": "Refused: {{receiver}} {{transport}} {{k8s_pod_name}}"
    }
   ]
  },
  {
   "title": "Metric Points ${metric:text} - $collector_pod_name",
   "type": "timeseries",
   "description": "Accepted: count/rate of metric points successfully pushed into the pipeline.\nRefused: count/rate of metric points that could not be pushed into the pipeline.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(${metric:value}(otelcol_receiver_accepted_metric_points_total{receiver=~\"$receiver\",k8s_cluster_name=\"$cluster\", k8s_pod_name=~\"$collector_pod_name\"}[2$__rate_interval])) by (receiver $grouping)",
     "legendFormat": "Accepted: {{receiver}} {{transport}} {{k8s_pod_name}}"
    },
    {
     "expr": "sum(${metric:value}(otelcol_receiver_refused_metric_points_total{receiver=~\"$receiver\",k8s_cluster_name=\"$cluster\", k8s_pod_name=~\"$collector_pod_name\"}[2$__rate_interval])) by (receiver $grouping)",
     "legendFormat": "Refused: {{receiver}} {{transport}} {{k8s_pod_name}}"
    }
   ]
  },
  {
   "title": "Log Records ${metric:text} - $collector_pod_name",
   "type": "timeseries",
   "description": "Accepted: count/rate of log records successfully pushed into the pipeline.\nRefused: count/rate of log records that could not be pushed into the pipeline.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(${metric:value}(otelcol_receiver_accepted_log_records_total{receiver=~\"$receiver\",k8s_cluster_name=\"$cluster\", k8s_pod_name=~\"$collector_pod_name\"}[2$__rate_interval])) by (receiver $grouping)",
     "legendFormat": "Accepted: {{receiver}} {{transport}} {{k8s_pod_name}}"
    },
    {
     "expr": "sum(${metric:value}(otelcol_receiver_refused_log_records_total{receiver=~\"$receiver\",k8s_cluster_name=\"$cluster\", k8s_pod_name=~\"$collector_pod_name\"}[2$__rate_interval])) by (receiver $grouping)",
     "legendFormat": "Refused: {{receiver}} {{transport}} {{k8s_pod_name}}"
    }
   ]
  },
  { "title": "Processors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Spans ${metric:text} - $collector_pod_name",
   "type": "timeseries",
   "description": "Accepted: count/rate of spans successfully pushed into the next component in the pipeline.\nRefused: count/rate of spans that were rejected by the next component in the pipeline.\nDropped: count/rate of spans that were dropped",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(${metric:value}(otelcol_processor_accepted_spans_total{processor=~\"$processor\",k8s_cluster_name=\"$cluster\", k8s_pod_name=~\"$collector_pod_name\"}[2$__rate_interval])) by (processor $grouping)",
     "legendFormat": "Accepted: {{processor}} {{k8s_pod_name}}"
    },
    {
     "expr": "sum(${metric:value}(otelcol_processor_refused_spans_total{processor=~\"$processor\",k8s_cluster_name=\"$cluster\", k8s_pod_name=~\"$collector_pod_name\"}[2$__rate_interval])) by (processor $grouping)",
     "legendFormat": "Refused: {{processor}}"
    },
    {
     "expr": "sum(${metric:value}(otelcol_processor_dropped_spans_total{processor=~\"$processor\",k8s_cluster_name=\"$cluster\", k8s_pod_name=~\"$collector_pod_name\"}[2$__rate_interval])) by (processor $grouping)",
     "legendFormat": "Dropped: {{processor}} {{k8s_pod_name}}"
    }
   ]
  },
  {
   "title": "Metric Points ${metric:text} - $collector_pod_name",
   "type": "timeseries",
   "description": "Accepted: count/rate of metric points successfully pushed into the next component in the pipeline.\nRefused: count/rate of metric points that were rejected by the next component in the pipeline.\nDropped: count/rate of metric points that were dropped",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(${metric:value}(otelcol_processor_accepted_metric_points_total{processor=~\"$processor\",k8s_cluster_name=\"$cluster\", k8s_pod_name=~\"$collector_pod_name\"}[2$__rate_interval])) by (processor $grouping)",
     "legendFormat": "Accepted: {{processor}} {{k8s_pod_name}}"
    },
    {
     "expr": "sum(${metric:value}(otelcol_processor_refused_metric_points_total{processor=~\"$processor\",k8s_cluster_name=\"$cluster\", k8s_pod_name=~\"$collector_pod_name\"}[2$__rate_interval])) by (processor $grouping)",
     "legendFormat": "Refused: {{processor}}"
    },
    {
     "expr": "sum(${metric:value}(otelcol_processor_dropped_metric_points_total{processor=~\"$processor\",k8s_cluster_name=\"$cluster\", k8s_pod_name=~\"$collector_pod_name\"}[2$__rate_interval])) by (processor)",
     "legendFormat": "Dropped: {{processor}} {{k8s_pod_name}}"
    }
   ]
  },
  {
   "title": "Log Records ${metric:text} - $collector_pod_name",
   "type": "timeseries",
   "description": "Accepted: count/rate of log records successfully pushed into the next component in the pipeline.\nRefused: count/rate of log records that were rejected by the next component in the pipeline.\nDropped: count/rate of log records that were dropped",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(${metric:value}(otelcol_processor_accepted_log_records_total{processor=~\"$processor\",k8s_cluster_name=\"$cluster\", k8s_pod_name=~\"$collector_pod_name\"}[2$__rate_interval])) by (processor $grouping)",
     "legendFormat": "Accepted: {{processor}} {{k8s_pod_name}}"
    },
    {
     "expr": "sum(${metric:value}(otelcol_processor_refused_log_records_total{processor=~\"$processor\",k8s_cluster_name=\"$cluster\", k8s_pod_name=~\"$collector_pod_name\"}[2$__rate_interval])) by (processor $grouping)",
     "legendFormat": "Refused: {{processor}}"
    },
    {
     "expr": "sum(${metric:value}(otelcol_processor_dropped_log_records_total{processor=~\"$processor\",k8s_cluster_name=\"$cluster\", k8s_pod_name=~\"$collector_pod_name\"}[2$__rate_interval])) by (processor)",
     "legendFormat": "Dropped: {{processor}} {{k8s_pod_name}}"
    }
   ]
  },
  {
   "title": "Batch Metrics - $collector_pod_name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(${metric:value}(otelcol_processor_batch_batch_send_size_count{processor=~\"$processor\",k8s_cluster_name=\"$cluster\", k8s_pod_name=~\"$collector_pod_name\"}[2$__rate_interval])) by (processor)",
     "legendFormat": "Batch send size count: {{processor}}"
    },
    {
     "expr": "sum(${metric:value}(otelcol_processor_batch_batch_send_size_sum{processor=~\"$processor\",k8s_cluster_name=\"$cluster\", k8s_pod_name=~\"$collector_pod_name\"}[2$__rate_interval])) by (processor)",
     "legendFormat": "Batch send size sum: {{processor}}"
    }
   ]
  },
  {
   "title": "Batch Send Size Heatmap - $collector_pod_name",
   "type": "heatmap",
   "description": "Number of units in the batch",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "expr": "sum(increase(otelcol_processor_batch_batch_send_size_bucket{processor=\"batch\",k8s_cluster_name=\"$cluster\", k8s_pod_name=~\"$collector_pod_name\"}[2$__rate_interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Batch Metrics - $collector_pod_name",
   "type": "timeseries",
   "description": "Number of times the batch was sent due to a size trigger. Number of times the batch was sent due to a timeout trigger.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(${metric:value}(otelcol_processor_batch_batch_size_trigger_send_total{processor=~\"$processor\",k8s_cluster_name=\"$cluster\", k8s_pod_name=~\"$collector_pod_name\"}[2$__rate_interval])) by (processor)",
     "legendFormat": "Batch sent due to a size trigger: {{processor}}"
    },
    {
     "expr": "sum(${metric:value}(otelcol_processor_batch_timeout_trigger_send{processor=~\"$processor\",k8s_cluster_name=\"$cluster\", k8s_pod_name=~\"$collector_pod_name\"}[2$__rate_interval])) by (processor)",
     "legendFormat": "Batch sent due to a timeout trigger: {{processor}}"
    }
   ]
  },
  { "title": "Exporters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Spans ${metric:text} - $collector_pod_name",
   "type": "timeseries",
   "description": "Sent: count/rate of spans successfully sent to destination.\nEnqueue: count/rate of spans failed to be added to the sending queue.\nFailed: count/rate of spans in failed attempts to send to destination.",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(${metric:value}(otelcol_exporter_sent_spans_total{exporter=~\"$exporter\",k8s_cluster_name=\"$cluster\", k8s_pod_name=~\"$collector_pod_name\"}[2$__rate_interval])) by (exporter $grouping)",
     "legendFormat": "Sent: {{exporter}} {{k8s_pod_name}}"
    },
    {
     "expr": "sum(${metric:value}(otelcol_exporter_enqueue_failed_spans_total{exporter=~\"$exporter\",k8s_cluster_name=\"$cluster\", k8s_pod_name=~\"$collector_pod_name\"}[2$__rate_interval])) by (exporter $grouping)",
     "legendFormat": "Enqueue: {{exporter}} {{k8s_pod_name}}"
    },
    {
     "expr": "sum(${metric:value}(otelcol_exporter_send_failed_spans_total{exporter=~\"$exporter\",k8s_cluster_name=\"$cluster\", k8s_pod_name=~\"$collector_pod_name\"}[2$__rate_interval])) by (exporter $grouping)",
     "legendFormat": "Failed: {{exporter}} {{k8s_pod_name}}"
    }
   ]
  },
  {
   "title": "Metric Points ${metric:text} - $collector_pod_name",
   "type": "timeseries",
   "description": "Sent: count/rate of metric points successfully sent to destination.\nEnqueue: count/rate of metric points failed to be added to the sending queue.\nFailed: count/rate of metric points in failed attempts to send to destination.",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(${metric:value}(otelcol_exporter_sent_metric_points_total{exporter=~\"$exporter\",k8s_cluster_name=\"$cluster\", k8s_pod_name=~\"$collector_pod_name\"}[2$__rate_interval])) by (exporter $grouping)",
     "legendFormat": "Sent: {{exporter}} {{k8s_pod_name}}"
    },
    {
     "expr": "sum(${metric:value}(otelcol_exporter_enqueue_failed_metric_points_total{exporter=~\"$exporter\",k8s_cluster_name=\"$cluster\", k8s_pod_name=~\"$collector_pod_name\"}[2$__rate_interval])) by (exporter $grouping)",
     "legendFormat": "Enqueue: {{exporter}} {{k8s_pod_name}}"
    },
    {
     "expr": "sum(${metric:value}(otelcol_exporter_send_failed_metric_points_total{exporter=~\"$exporter\",k8s_cluster_name=\"$cluster\", k8s_pod_name=~\"$collector_pod_name\"}[2$__rate_interval])) by (exporter $grouping)",
     "legendFormat": "Failed: {{exporter}} {{k8s_pod_name}}"
    }
   ]
  },
  {
   "title": "Log Records ${metric:text}",
   "type": "timeseries",
   "description": "Sent: count/rate of log records successfully sent to destination.\nEnqueue: count/rate of log records failed to be added to the sending queue.\nFailed: count/rate of log records in failed attempts to send to destination.",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(${metric:value}(otelcol_exporter_sent_log_records_total{exporter=~\"$exporter\",k8s_cluster_name=\"$cluster\"}[2$__rate_interval])) by (exporter $grouping)",
     "legendFormat": "Sent: {{exporter}} {{k8s_pod_name}}"
    },
    {
     "expr": "sum(${metric:value}(otelcol_exporter_enqueue_failed_log_records_total{exporter=~\"$exporter\",k8s_cluster_name=\"$cluster\"}[2$__rate_interval])) by (exporter $grouping)",
     "legendFormat": "Enqueue: {{exporter}} {{k8s_pod_name}}"
    },
    {
     "expr": "sum(${metric:value}(otelcol_exporter_send_failed_log_records_total{exporter=~\"$exporter\",k8s_cluster_name=\"$cluster\"}[2$__rate_interval])) by (exporter $grouping)",
     "legendFormat": "Failed: {{exporter}} {{k8s_pod_name}}"
    }
   ]
  },
  {
   "title": "Exporter Queue Size - $collector_pod_name",
   "type": "timeseries",
   "description": "Current size of the retry queue (in batches)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(otelcol_exporter_queue_size{exporter=~\"$exporter\",k8s_cluster_name=\"$cluster\", k8s_pod_name=~\"$collector_pod_name\"}) by (exporter)",
     "legendFormat": "Max queue size: {{exporter}}"
    }
   ]
  },
  {
   "title": "Exporter Queue Capacity - $collector_pod_name",
   "type": "timeseries",
   "description": "Fixed capacity of the retry queue (in batches)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min(otelcol_exporter_queue_capacity{exporter=~\"$exporter\",k8s_cluster_name=\"$cluster\", k8s_pod_name=~\"$collector_pod_name\"}) by (exporter)",
     "legendFormat": "Queue capacity: {{exporter}}"
    }
   ]
  },
  {
   "title": "Collector",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total RSS Memory - $collector_pod_name",
     "type": "timeseries",
     "description": "Total physical memory (resident set size)",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 141 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max(otelcol_process_memory_rss{k8s_cluster_name=\"$cluster\", k8s_pod_name=~\"$collector_pod_name\"}) by (job $grouping)",
       "legendFormat": "Max Memory RSS {{k8s_pod_name}}"
      },
      {
       "expr": "avg(otelcol_process_memory_rss{k8s_cluster_name=\"$cluster\", k8s_pod_name=~\"$collector_pod_name\"}) by (job $grouping)",
       "legendFormat": "Avg Memory RSS {{k8s_pod_name}}"
      },
      {
       "expr": "min(otelcol_process_memory_rss{k8s_cluster_name=\"$cluster\", k8s_pod_name=~\"$collector_pod_name\"}) by (job $grouping)",
       "legendFormat": "Min Memory RSS {{k8s_pod_name}}"
      }
     ]
    },
    {
     "title": "Total Runtime Sys Memory - $collector_pod_name",
     "type": "timeseries",
     "description": "Total bytes of memory obtained from the OS (see 'go doc runtime.MemStats.Sys')",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 141 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max(otelcol_process_runtime_total_sys_memory_bytes{k8s_cluster_name=\"$cluster\", k8s_pod_name=~\"$collector_pod_name\"}) by (job $grouping)",
       "legendFormat": "Max Memory RSS {{k8s_pod_name}}"
      },
      {
       "expr": "avg(otelcol_process_runtime_total_sys_memory_bytes{k8s_cluster_name=\"$cluster\", k8s_pod_name=~\"$collector_pod_name\"}) by (job $grouping)",
       "legendFormat": "Avg Memory RSS {{k8s_pod_name}}"
      },
      {
       "expr": "min(otelcol_process_runtime_total_sys_memory_bytes{k8s_cluster_name=\"$cluster\", k8s_pod_name=~\"$collector_pod_name\"}) by (job $grouping)",
       "legendFormat": "Min Memory RSS {{k8s_pod_name}}"
      }
     ]
    },
    {
     "title": "Total Runtime Heap Memory - $collector_pod_name",
     "type": "timeseries",
     "description": "Bytes of allocated heap objects (see 'go doc runtime.MemStats.HeapAlloc')",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 141 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max(otelcol_process_runtime_heap_alloc_bytes{k8s_cluster_name=\"$cluster\", k8s_pod_name=~\"$collector_pod_name\"}) by (job $grouping)",
       "legendFormat": "Max Memory RSS {{k8s_pod_name}}"
      },
      {
       "expr": "avg(otelcol_process_runtime_heap_alloc_bytes{k8s_cluster_name=\"$cluster\", k8s_pod_name=~\"$collector_pod_name\"}) by (job $grouping)",
       "legendFormat": "Avg Memory RSS {{k8s_pod_name}}"
      },
      {
       "expr": "min(otelcol_process_runtime_heap_alloc_bytes{k8s_cluster_name=\"$cluster\", k8s_pod_name=~\"$collector_pod_name\"}) by (job $grouping)",
       "legendFormat": "Min Memory RSS {{k8s_pod_name}}"
      }
     ]
    },
    {
     "title": "CPU Usage - $collector_pod_name",
     "type": "timeseries",
     "description": "Total CPU user and system time in percentage",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 150 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "max(rate(otelcol_process_cpu_seconds_total{k8s_cluster_name=\"$cluster\", k8s_pod_name=~\"$collector_pod_name\"}[2$__rate_interval])*100) by (job $grouping)",
       "legendFormat": "Max CPU usage {{k8s_pod_name}}"
      },
      {
       "expr": "avg(rate(otelcol_process_cpu_seconds_total{k8s_cluster_name=\"$cluster\", k8s_pod_name=~\"$collector_pod_name\"}[2$__rate_interval])*100) by (job $grouping)",
       "legendFormat": "Avg CPU usage {{k8s_pod_name}}"
      },
      {
       "expr": "min(rate(otelcol_process_cpu_seconds_total{k8s_cluster_name=\"$cluster\", k8s_pod_name=~\"$collector_pod_name\"}[2$__rate_interval])*100) by (job $grouping)",
       "legendFormat": "Min CPU usage {{k8s_pod_name}}"
      }
     ]
    },
    {
     "title": "Collector pod count",
     "type": "timeseries",
     "description": "Number of collector pods, which are reporting metrics",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 150 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count(count(otelcol_process_cpu_seconds_total{k8s_cluster_name=\"$cluster\", k8s_pod_name=~\"$collector_pod_name\"}) by (k8s_pod_name))",
       "legendFormat": "collector pod count"
      }
     ]
    },
    {
     "title": "Uptime by collector pod name",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 150 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(otelcol_process_uptime_seconds_total{k8s_cluster_name=\"$cluster\", k8s_pod_name=~\"$collector_pod_name\"}) by (k8s_pod_name)",
       "legendFormat": "{{k8s_pod_name}}"
      }
     ]
    },
    {
     "title": "Collector pod info",
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 159 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(otelcol_process_uptime_seconds_total{k8s_cluster_name=\"$cluster\", k8s_pod_name=~\"$collector_pod_name\"}) by (k8s_pod_name,service_version)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Signal Flows",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Spans Flow - $collector_pod_name",
     "type": "nodeGraph",
     "description": "Receivers -> Processor(s) -> Exporters (Node Graph panel is beta, so this panel may not show data correctly).",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 165 },
     "targets": [
      {
       "expr": "# receivers\nlabel_replace(\n  label_join(\n    label_join(\n      sum(${metric:value}(\n        otelcol_receiver_accepted_spans_total{receiver=~\"$receiver\",k8s_cluster_name=\"$cluster\", k8s_pod_name=~\"$collector_pod_name\"}[2m])\n      ) by (receiver)\n      , \"id\", \"-rcv-\", \"transport\", \"receiver\"\n    )\n    , \"title\", \"\", \"transport\", \"receiver\"\n  )\n  , \"icon\", \"arrow-to-right\", \"\", \"\"\n)\n\n# dummy processor\nor\nlabel_replace(\n  label_replace(\n    label_replace(\n      (sum(rate(otelcol_process_uptime_seconds_total{k8s_cluster_name=\"$cluster\", k8s_pod_name=~\"$collector_pod_name\"}[2m])))\n      , \"id\", \"processor\", \"\", \"\"\n    )\n    , \"title\", \"Processor(s)\", \"\", \"\"\n  )\n  , \"icon\", \"arrow-random\", \"\", \"\"\n)\n\n# exporters\nor\nlabel_replace(\n  label_join(\n    label_join(\n      sum(${metric:value}(\n        otelcol_exporter_sent_spans_total{exporter=~\"$exporter\",k8s_cluster_name=\"$cluster\", k8s_pod_name=~\"$collector_pod_name\"}[2m])\n      ) by (exporter)\n      , \"id\", \"-exp-\", \"transport\", \"exporter\"\n    )\n    , \"title\", \"\", \"transport\", \"exporter\"\n  )\n  , \"icon\", \"arrow-from-right\", \"\", \"\"\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "# receivers -> processor\r\nlabel_join(\r\n    label_replace(\r\n        label_join(\r\n            (sum(rate(otelcol_receiver_accepted_spans_total{k8s_cluster_name=\"$cluster\", k8s_pod_name=~\"$collector_pod_name\"}[2m])) by (receiver))\r\n            ,\"source\", \"-rcv-\", \"transport\", \"receiver\"\r\n        )\r\n        ,\"target\", \"processor\", \"\", \"\"\r\n    )\r\n    , \"id\", \"-\", \"source\", \"target\"\r\n)\r\n\r\n# processor -> exporters\r\nor\r\nlabel_join(\r\n    label_replace(\r\n        label_join(\r\n            (sum(rate(otelcol_exporter_sent_spans_total{k8s_cluster_name=\"$cluster\", k8s_pod_name=~\"$collector_pod_name\"}[2m])) by (exporter))\r\n            , \"target\", \"-exp-\", \"transport\", \"exporter\"\r\n        )\r\n        , \"source\", \"processor\", \"\", \"\"\r\n    )\r\n    , \"id\", \"-\", \"source\", \"target\"\r\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Metric Points Flow - $collector_pod_name",
     "type": "nodeGraph",
     "description": "Receivers -> Processor(s) -> Exporters (Node Graph panel is beta, so this panel may not show data correctly).",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 165 },
     "targets": [
      {
       "expr": "# receivers\nlabel_replace(\n  label_join(\n    label_join(\n      (sum(\n        ${metric:value}(otelcol_receiver_accepted_metric_points_total{receiver=~\"$receiver\",k8s_cluster_name=\"$cluster\", k8s_pod_name=~\"$collector_pod_name\"}[2m])\n      ) by (receiver))\n      , \"id\", \"-rcv-\", \"transport\", \"receiver\"\n    )\n    , \"title\", \"\", \"transport\", \"receiver\"\n  )\n  , \"icon\", \"arrow-to-right\", \"\", \"\"\n)\n\n# dummy processor\nor\nlabel_replace(\n  label_replace(\n    label_replace(\n      (sum(rate(otelcol_process_uptime_seconds_total{k8s_cluster_name=\"$cluster\", k8s_pod_name=~\"$collector_pod_name\"}[2m])))\n      , \"id\", \"processor\", \"\", \"\"\n    )\n    , \"title\", \"Processor(s)\", \"\", \"\"\n  )\n  , \"icon\", \"arrow-random\", \"\", \"\"\n)\n\n# exporters\nor\nlabel_replace(\n  label_join(\n    label_join(\n      (sum(\n        ${metric:value}(otelcol_exporter_sent_metric_points_total{exporter=~\"$exporter\",k8s_cluster_name=\"$cluster\", k8s_pod_name=~\"$collector_pod_name\"}[2m])\n      ) by (exporter))\n      , \"id\", \"-exp-\", \"transport\", \"exporter\"\n    )\n    , \"title\", \"\", \"transport\", \"exporter\"\n  )\n  , \"icon\", \"arrow-from-right\", \"\", \"\"\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "# receivers -> processor\r\nlabel_join(\r\n    label_replace(\r\n        label_join(\r\n            (sum(rate(otelcol_receiver_accepted_metric_points_total{k8s_cluster_name=\"$cluster\", k8s_pod_name=~\"$collector_pod_name\"}[2m])) by (receiver))\r\n            , \"source\", \"-rcv-\", \"transport\", \"receiver\"\r\n        )\r\n        , \"target\", \"processor\", \"\", \"\"\r\n    )\r\n    , \"id\", \"-\", \"source\", \"target\"\r\n)\r\n\r\n# processor -> exporters\r\nor \r\nlabel_join(\r\n    label_replace(\r\n        label_join(\r\n            (sum(rate(otelcol_exporter_sent_metric_points_total{k8s_cluster_name=\"$cluster\", k8s_pod_name=~\"$collector_pod_name\"}[2m])) by (exporter))\r\n            , \"target\", \"-exp-\", \"transport\", \"exporter\"\r\n        )\r\n        , \"source\", \"processor\", \"\", \"\"\r\n    )\r\n    , \"id\", \"-\", \"source\", \"target\"\r\n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Log Records Flow - $collector_pod_name",
     "type": "nodeGraph",
     "description": "Receivers -> Processor(s) -> Exporters (Node Graph panel is beta, so this panel may not show data correctly).",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 165 },
     "targets": [
      {
       "expr": "# receivers\nlabel_replace(\n  label_join(\n    label_join(\n      sum(${metric:value}(\n        otelcol_receiver_accepted_log_records_total{receiver=~\"$receiver\",k8s_cluster_name=\"$cluster\", k8s_pod_name=~\"$collector_pod_name\"}[2m])\n      ) by (receiver)\n      , \"id\", \"-rcv-\", \"transport\", \"receiver\"\n    )\n    , \"title\", \"\", \"transport\", \"receiver\"\n  )\n  , \"icon\", \"arrow-to-right\", \"\", \"\"\n)\n\n# dummy processor\nor\nlabel_replace(\n  label_replace(\n    label_replace(\n      (sum(rate(otelcol_process_uptime_seconds_total{k8s_cluster_name=\"$cluster\", k8s_pod_name=~\"$collector_pod_name\"}[2m])))\n      , \"id\", \"processor\", \"\", \"\"\n    )\n    , \"title\", \"Processor(s)\", \"\", \"\"\n  )\n  , \"icon\", \"arrow-random\", \"\", \"\"\n)\n\n# exporters\nor\nlabel_replace(\n  label_join(\n    label_join(\n      sum(${metric:value}(\n        otelcol_exporter_sent_log_records_total{exporter=~\"$exporter\",k8s_cluster_name=\"$cluster\", k8s_pod_name=~\"$collector_pod_name\"}[2m])\n      ) by (exporter)\n      , \"id\", \"-exp-\", \"transport\", \"exporter\"\n    )\n    , \"title\", \"\", \"transport\", \"exporter\"\n  )\n  , \"icon\", \"arrow-from-right\", \"\", \"\"\n)",
       "legendFormat": "__auto"
      },
      {
       "expr": "# receivers -> processor\r\nlabel_join(\r\n    label_replace(\r\n        label_join(\r\n            (sum(rate(otelcol_receiver_accepted_log_records_total{k8s_cluster_name=\"$cluster\", k8s_pod_name=~\"$collector_pod_name\"}[2m])) by (receiver))\r\n            , \"source\", \"-rcv-\", \"transport\", \"receiver\"\r\n        )\r\n        , \"target\", \"processor\", \"\", \"\"\r\n    )\r\n    , \"id\", \"-edg-\", \"source\", \"target\"\r\n)\r\n\r\n# processor -> exporters\r\nor \r\nlabel_join(\r\n    label_replace(\r\n        label_join(\r\n            (sum(rate(otelcol_exporter_sent_log_records_total{k8s_cluster_name=\"$cluster\", k8s_pod_name=~\"$collector_pod_name\"}[2m])) by (exporter))\r\n            ,\"target\",\"-exp-\",\"transport\",\"exporter\"\r\n        )\r\n        ,\"source\",\"processor\",\"\",\"\"\r\n    )\r\n    ,\"id\",\"-edg-\",\"source\",\"target\"\r\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Kubernetes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Namespaces",
     "type": "timeseries",
     "description": "Added: Number of namespace add events received.\nUpdated: Number of namespace update events received.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "avg(otelcol_otelsvc_k8s_namespace_added_total) by (job $grouping)",
       "legendFormat": "Added: {{transport}} {{k8s_pod_name}}"
      },
      {
       "expr": "avg(otelcol_otelsvc_k8s_namespace_updated_total) by (job $grouping)",
       "legendFormat": "Updated: {{transport}} {{k8s_pod_name}}"
      }
     ]
    },
    {
     "title": "Pods",
     "type": "timeseries",
     "description": "Added: Number of pod add events received.\nUpdated: Number of pod update events received.\nDeleted: Number of pod delete events received.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(otelcol_otelsvc_k8s_pod_added_total) by (job $grouping)",
       "legendFormat": "Added: {{transport}} {{k8s_pod_name}}"
      },
      {
       "expr": "sum(otelcol_otelsvc_k8s_pod_updated_total) by (job $grouping)",
       "legendFormat": "Updated: {{transport}} {{k8s_pod_name}}"
      },
      {
       "expr": "sum(otelcol_otelsvc_k8s_pod_deleted_total) by (job $grouping)",
       "legendFormat": "Deleted: {{transport}} {{k8s_pod_name}}"
      }
     ]
    }
   ]
  },
  { "title": "Documentation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Documentation",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 49 },
   "options": {
    "content": "<a href=\"http://www.monitoringartist.com\" target=\"_blank\" title=\"Dashboard maintained by Monitoring Artist - DevOps / Docker / Kubernetes / AWS ECS / Google GCP / Zabbix / Zenoss / Terraform / Monitoring\"><img src=\"https://monitoringartist.github.io/monitoring-artist-logo-grafana.png\" height=\"30px\" /></a> | \n<a target=\"_blank\" href=\"https://github.com/open-telemetry/opentelemetry-collector/blob/main/docs/troubleshooting.md#metrics\">OTEL collector troubleshooting (how to enable telemetry metrics)</a> | \n<a target=\"_blank\" href=\"https://opentelemetry.io/docs/collector/scaling/\">Scaling the Collector (metrics to watch)</a> | \n<a target=\"_blank\" href=\"https://grafana.com/grafana/dashboards/15983-opentelemetry-collector/\">Installed from Grafana.com dashboards</a>"
   }
  }
 ]
}